### ISSUE TITLE
弹幕消息 cmd 更改为 DANMU_MSG:4:0:2:2:2:0 适配

### ISSUE THREAD

**Issue by ddiu8081** [starknt/tiny-bilibili-ws#1]
或许是近日临时举措，b 站关闭了漂浮弹幕，使用原来的 `DANMU_MSG` 监听不到消息了，改为 `DANMU_MSG:4:0:2:2:2:0`。

研究了下 bilibili-live-ws 做了[一些适配](https://github.com/simon300000/bilibili-live-ws/blob/422f40aede86dfe1ee427a30fbd696220e5b7aba/src/common.ts#L65-L71)，会把以 `DANMU_MSG` 开头的消息都当作 `DANMU_MSG`，从而能够继续监听到

```ts
if (cmd) {
  if (cmd.includes('DANMU_MSG')) {
    this.emit('DANMU_MSG', data)
  } else {
    this.emit(cmd, data)
  }
}
```

这个库是否也可以做类似的处理？

相关 issue: https://github.com/ddiu8081/blive-message-listener/issues/14

**Comment by starknt** [comment]
好的

**Comment by starknt** [comment]
> 

刚刚去测试了一下，弹幕消息似乎恢复到 `DANMU_MSG` 了
