### ISSUE TITLE
是否无法支持短房号？

### ISSUE THREAD

**Issue by Nauxscript** [starknt/tiny-bilibili-ws#2]
发现有些房间的房间号是比较短的，房号只有 3、4 位（好像是排行榜靠前的或者一些比较火的主播会有这样的房间号），通过这种短的房号无法抓到弹幕；不知道是什么原因呢？有点疑惑；有没有一些解决方法？

**Comment by starknt** [comment]
需要通过 getLongRoomId API 获取长房间号才行，但是因为跨域问题，这个API在浏览器上用不了

**Comment by Nauxscript** [comment]
好的 十分感谢~
