### ISSUE TITLE
当前的连接弹幕的方法可能不太稳定

### ISSUE THREAD

**Issue by Danjuanlab** [starknt/tiny-bilibili-ws#5]
![无标题](https://github.com/starknt/tiny-bilibili-ws/assets/42509669/24c6bd37-474d-4b19-9c62-0ca566573021)
如图，昨晚测试的时候发现信息都是能同步B站直播间的，今天测试的时候却发现弹幕监听延迟非常大，同时只能偶尔零星的收到部分弹幕。

**Comment by wuXinnnn** [comment]
这应该是今天的突发问题，过去在使用中从未遇到过，今天有一些其他库也发生了同样的情况，我也正在查原因

**Comment by starknt** [comment]
应该是b站问题吧，我看直播的时候都看不到弹幕

**Comment by harryisfish** [comment]
我从 [这个listener](https://github.com/ddiu8081/blive-message-listener) 过来的，好像也是用了这个 ws 库。
最近几天会出现程序报连接到弹幕服务了，但是收不到弹幕推送的问题。
期待大佬们定位一下问题。

[issue of 连接和心跳包都是正常的，但获取不到弹幕的推送](https://github.com/simon300000/bilibili-live-ws/issues/401)

**Comment by 1962247851** [comment]
这个问题我也遇到了，可以参考一下我的解决方法：https://github.com/OrdinaryRoad-Project/ordinaryroad-bilibili-live/commit/8cd06ffbe62e3582c514679ff837781da6ce392b

**Comment by starknt** [comment]
> 这个问题我也遇到了，可以参考一下我的解决方法：[OrdinaryRoad-Project/ordinaryroad-bilibili-live@8cd06ff](https://github.com/OrdinaryRoad-Project/ordinaryroad-bilibili-live/commit/8cd06ffbe62e3582c514679ff837781da6ce392b)

在 NodeJS 能这样能行，但是在浏览器中因为跨域问题，似乎没有更好的办法
