### ISSUE TITLE
关于cookie的使用方式？

### ISSUE THREAD

**Issue by eric2788** [starknt/tiny-bilibili-ws#7]
没了解过 websocket 如何分辨登入方式，但假设我手上有 b 站账户的 cookie, 我可以怎么传入到这个库里面（又或者怎么让它成为登入状态）？

**Comment by starknt** [comment]
抱歉，鸽的有点久了，后面会在文档中补充相关的信息，应该会在这几天内完成^_^

**Comment by eric2788** [comment]
好好好 也不算急 等你完成文檔可以直接把issue關了
