### ISSUE TITLE
配置相关key,buvid等参数后弹幕仍丢失严重

### ISSUE THREAD

**Issue by renmu123** [starknt/tiny-bilibili-ws#9]
我分别使用了 `tiny-bilibili-ws:1.0.0` 和 `bilibili-live-ws:6.3.1` ，在参数尽可能保持相同的情况下，tiny-bilibili-ws的丢弹幕情况严重，bilibili-live-ws是正常的，部分敏感参数只能看到部分，但也能看出是保持一致的
![图片](https://github.com/user-attachments/assets/c222c886-6c80-4ed5-85d4-0de542e2b3d7)

**Comment by renmu123** [comment]
<img width="1733" alt="Snipaste_2024-11-06_22-41-34" src="https://github.com/user-attachments/assets/7035fd00-4fe0-4ce2-b856-d45694474df0">

抓包之后发现接口返回的包几乎是相同的，但是有些数据没解析成功？我倾向于认证没问题，解析部分出错了

**Comment by starknt** [comment]
我昨天测试也在怀疑这个问题，尝试退回旧版的数据包解析逻辑了

**Comment by starknt** [comment]
发布了 `1.0.1.beta.1`

**Comment by renmu123** [comment]
新版本测试了几分钟，一切正常

**Comment by starknt** [comment]
好
